model:
  type_optim: 'adam'
  base_learning_rate: 0.00001
  weight_decay: 0.0004
  gamma: 0.3
  tau: [1000]
  scheduler: "step"
  target: models.dml_trainer.DML_Model
  params:
    config:
      Architecture:
        target: architectures.bninception.Network
        params:
          pretraining: "imagenet"
          embed_dim: -1 # 512
          arch: "bninception_frozen_normalize" #"bninception_frozen_normalize", vit_small_patch16_224_normalize
          VQ: True
          n_e: 1000
          e_dim: 1024
          beta: 0.25

      Vectorquantizer:
        target: architectures.VQ.VectorQuantizer
        params:
          n_e: 1000
          e_dim: 1024
          beta: 0.25

      Loss:
        target: criteria.select
        name: "multisimilarity"
        params:
          name: "multisimilarity"
          batchminer:
          n_classes: -1
          loss_multisimilarity_pos_weight: 2
          loss_multisimilarity_neg_weight: 40
          loss_multisimilarity_margin: 0.1
          loss_multisimilarity_pos_thresh: 0.5
          loss_multisimilarity_neg_thresh: 0.5
          loss_multisimilarity_base_mode: 1
          loss_multisimilarity_d_mode: 'cosine'


      Evaluation:
        target: metrics.metric_computer.MetricComputer
        params:
          metric_names: ["e_recall@1", "nmi"]
          n_classes: -1
          evaluate_on_gpu: True
          num_workers: 0

      CustomLogs:
        target: models.log.custom_logging

data:
  target: data.base.DataModuleFromConfig
  params:
    batch_size: 112
    num_workers: 20

    train:
      target: data.CUB200.DATA
      params: 
        root:
        train: True
        ooDML_split_id: -1
        arch: "bninception_frozen_normalize" # vit_small_patch16_224_normalize
      data_sampler:
        target: datasampler.select
        params:
          name: "class_random"
          samples_per_class: 2

    validation:
      target: data.CUB200.DATA
      params:
        root:
        train: False
        ooDML_split_id: -1
        arch: "bninception_frozen_normalize" # vit_small_patch16_224_normalize

lightning:
  trainer:
    strategy: 'ddp' #
    replace_sampler_ddp: False
    # accumulate_grad_batches: 1
    auto_scale_batch_size: false
    benchmark: False
    deterministic: True
    amp_backend: 'native'
    #amp_level: '02'
    log_every_n_steps: 25
    check_val_every_n_epoch: 1
    max_epochs: 100
    num_sanity_val_steps: -1

  logger:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      wandb_key: d84d1363e77cf0020a24401aaac1ad22ed7b3388
      project: Debug
      group:
      savename:

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: ''
      filename: 'recall@1{val/e_recall@1:.4f}'
      monitor: 'val/e_recall@1'
      mode: max
      every_n_epochs: 1
      verbose: True
      save_last: True
      save_top_k: 1
  
  callbacks:
#    earlystopcallback:
#      target: utils.callbacks.EarlyStoppingPL
#      params:
#        monitor: 'val/accuracy'
#        min_delta: 0.0001
